model:
  cldm:
    target: diffbir.model.cldm.ControlLDM
    params:
      latent_scale_factor: 0.18215
      unet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      controlnet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  diffusion:
    target: diffbir.model.gaussian_diffusion.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000
      zero_snr: True #False
      parameterization: v #eps

dataset:
  test:
    target: diffbir.dataset.codeformer.CodeformerDataset
    params:
      file_gt: /media/xjtu-ei/Disk_8T/LJH/Datasets/Natura_datasets/Div2K_Flick2K_train_Size_512_640_800 # /media/xjtu-ei/Disk_8T/LJH/Datasets/Natura_datasets/open-images-5W_crop_640  #Flickr2K_HR  #DIV2K_train_HR  #/usr/mlkkIC/Natura_datasets/open-images-30W_crop_256
      file_lq: /media/xjtu-ei/Disk_8T/LJH/LIC/LIC_TCM-main/results_test/Div2K_Flick2K_train_Size_512_640_800  #_0.00015  #/media/xjtu-ei/Disk_8T/LJH/Datasets/Natura_datasets/LQ_dataset/open-images-5W_crop_640_TCM/0005checkpoint_best  # /usr/mlkkIC/Natura_datasets/open-images-5W_crop_640  #Flickr2K_HR #/usr/mlkkIC/Natura_datasets/LQ_dataset/DIV2K_train_HR_LIC_TCM/0025  #/usr/mlkkIC/Natura_datasets/LQ_dataset/open-images-30W_crop_256_TCM_0025/0025

      file_backend_cfg:
        target: diffbir.dataset.file_backend.HardDiskBackend
      out_size: 512
      crop_type: random
      random_flag: False
      Target_training: True
#      prompt_case: "0025"   #   assert prompt_case in ["0005", "0025", "0067", "025"]
      blur_kernel_size: 41
      kernel_list: [ 'iso', 'aniso' ]
      kernel_prob: [ 0.5, 0.5 ]
      blur_sigma: [ 0.1, 12 ]
      downsample_range: [ 1, 12 ]
      noise_range: [ 0, 15 ]
      jpeg_range: [ 30, 100 ]

batch_transform:
  target: diffbir.dataset.batch_transform.IdentityBatchTransform

test:
  # pretrained sd v2.1 path
  sd_path: ./weights/v2-1_512-ema-pruned.ckpt
  # experiment directory path
  controlnet_ckpt: /media/xjtu-ei/Disk_8T/LJH/Compression_mlkk/img_recover/DiffBIR-main/experiment_0.0005_wo_llpips_wo_DSM/checkpoints/0298000.pt  #  2025年3月12日 0280000.pt 还可以
#  controlnet_ckpt: /media/xjtu-ei/Disk_8T/LJH/Compression_mlkk/img_recover/DiffBIR-main/experiment_0.00025/checkpoints/0294000.pt  #  2025年3月14日 0294000.pt 还可以
#  controlnet_ckpt: /media/xjtu-ei/Disk_8T/LJH/Compression_mlkk/img_recover/DiffBIR-main/experiment_0.001/checkpoints/0294000.pt  #  2025年3月14日 0294000.pt 还可以
#  controlnet_ckpt: /media/xjtu-ei/Disk_8T/LJH/Compression_mlkk/img_recover/DiffBIR-main/experiment_0.00015/checkpoints/0308000.pt  #  2025年3月14日 0308000.pt 还可以
#  output: results/Tecnick_TCM_0005_LDM_0.0570_lpips_S50
#  output: results/kodak_0.00015_bpp0.0202_real_S50_0310000
#  output: results/Tecnick_0.00015_bpp0.0266_real_S50_0308000
#  output: results/Tecnick_0.00015_bpp0.0266_real_S50_0308000
#  output: results/Tecnick_0.00025_bpp0.0357_real_S50_0294000
#  output: results/CLIC_2020_0.00015_bpp0.0204_real_S50_0294000
#  output: results/CLIC_2020_0.00025_bpp_0.0281real_S50_0294000
  output: results/train_data_0.0005_wo_llpips_wo_DSM/  #CLIC_2020_0.0005_bpp_0.0484_real_S50_0294000
#  output: results/kodak_TCM_0005_LDM_0.0513_lpips #GAN
#  output: results/kodak_TCM_kodak_0.001_bpp0.0841_real_lpips #GAN
#  output: results/kodak_TCM_00025_LDM_0.0289_lpips_step50 #GAN


